// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotifyDataAnalysis.Modules.Catalog.Infrastructure.Persistence;

#nullable disable

namespace SpotifyDataAnalysis.Modules.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260730195528_MapAudioFeaturesJsonProperties")]
    partial class MapAudioFeaturesJsonProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotifyDataAnalysis.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at_utc IS NULL AND dead_lettered_at_utc IS NULL");

                    b.ToTable("outbox_messages", "catalog");
                });

            modelBuilder.Entity("SpotifyDataAnalysis.Modules.Catalog.Domain.Albums.Album", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("EnrichmentAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("enrichment_attempts");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enriched");

                    b.Property<DateTime?>("LastEnrichmentAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_enrichment_attempt_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("name");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("integer")
                        .HasColumnName("total_tracks");

                    b.HasKey("Id")
                        .HasName("pk_albums");

                    b.HasIndex("IsEnriched", "EnrichmentAttempts")
                        .HasDatabaseName("ix_albums_enrichment_pending");

                    b.ToTable("albums", "catalog");
                });

            modelBuilder.Entity("SpotifyDataAnalysis.Modules.Catalog.Domain.Artists.Artist", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<int>("EnrichmentAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("enrichment_attempts");

                    b.Property<int>("Followers")
                        .HasColumnType("integer")
                        .HasColumnName("followers");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enriched");

                    b.Property<DateTime?>("LastEnrichmentAttemptUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_enrichment_attempt_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("name");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("_genres")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("genres");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("IsEnriched", "EnrichmentAttempts")
                        .HasDatabaseName("ix_artists_enrichment_pending");

                    b.ToTable("artists", "catalog");
                });

            modelBuilder.Entity("SpotifyDataAnalysis.Modules.Catalog.Domain.Playlists.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastIngestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_ingested_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerDisplayName")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("owner_display_name");

                    b.Property<string>("_trackIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("track_ids");

                    b.HasKey("Id")
                        .HasName("pk_playlists");

                    b.ToTable("playlists", "catalog");
                });

            modelBuilder.Entity("SpotifyDataAnalysis.Modules.Catalog.Domain.Tracks.Track", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<string>("AlbumId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("album_id");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<bool>("Explicit")
                        .HasColumnType("boolean")
                        .HasColumnName("explicit");

                    b.Property<string>("Isrc")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isrc");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("match_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("name");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("_artists")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("artists");

                    b.HasKey("Id")
                        .HasName("pk_tracks");

                    b.HasIndex("Isrc")
                        .HasDatabaseName("ix_tracks_isrc");

                    b.HasIndex("MatchKey")
                        .HasDatabaseName("ix_tracks_match_key");

                    b.ToTable("tracks", "catalog");
                });

            modelBuilder.Entity("SpotifyDataAnalysis.Modules.Catalog.Domain.Albums.Album", b =>
                {
                    b.OwnsOne("SpotifyDataAnalysis.Modules.Catalog.Domain.Albums.ReleaseDate", "ReleaseDate", b1 =>
                        {
                            b1.Property<string>("AlbumId")
                                .HasColumnType("character varying(64)");

                            b1.Property<DateOnly?>("ExactDate")
                                .HasColumnType("date")
                                .HasColumnName("release_date");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("release_precision");

                            b1.Property<string>("Raw")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("release_date_raw");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("release_year");

                            b1.HasKey("AlbumId");

                            b1.HasIndex("Year")
                                .HasDatabaseName("ix_albums_release_year");

                            b1.ToTable("albums", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("AlbumId");
                        });

                    b.Navigation("ReleaseDate");
                });

            modelBuilder.Entity("SpotifyDataAnalysis.Modules.Catalog.Domain.Tracks.Track", b =>
                {
                    b.OwnsOne("SpotifyDataAnalysis.Modules.Catalog.Domain.Tracks.AudioFeatures", "AudioFeatures", b1 =>
                        {
                            b1.Property<string>("TrackId")
                                .HasColumnType("character varying(64)");

                            b1.Property<double>("Acousticness")
                                .HasColumnType("double precision");

                            b1.Property<double>("Danceability")
                                .HasColumnType("double precision");

                            b1.Property<double>("Energy")
                                .HasColumnType("double precision");

                            b1.Property<string>("Genre")
                                .HasColumnType("text");

                            b1.Property<double>("Instrumentalness")
                                .HasColumnType("double precision");

                            b1.Property<bool>("IsImputed")
                                .HasColumnType("boolean");

                            b1.Property<int>("Key")
                                .HasColumnType("integer");

                            b1.Property<double>("Liveness")
                                .HasColumnType("double precision");

                            b1.Property<double>("Loudness")
                                .HasColumnType("double precision");

                            b1.Property<int>("Mode")
                                .HasColumnType("integer");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<double>("Speechiness")
                                .HasColumnType("double precision");

                            b1.Property<double>("Tempo")
                                .HasColumnType("double precision");

                            b1.Property<int>("TimeSignature")
                                .HasColumnType("integer");

                            b1.Property<double>("Valence")
                                .HasColumnType("double precision");

                            b1.HasKey("TrackId");

                            b1.ToTable("tracks", "catalog");

                            b1.ToJson("audio_features");

                            b1.WithOwner()
                                .HasForeignKey("TrackId");
                        });

                    b.Navigation("AudioFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
